spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}?currentSchema=${APP_SCHEMA}

    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}

    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: AppPool

  application:
    name: shopping-cart-service

  flyway:
    enabled: true
    schemas: ${APP_SCHEMA}